import {
  JobApplication,
  ThesisInfo,
  ModelExperiment,
  ResearchProject,
  MilestoneItem,
  LeetCodeItem,
  KnowledgeFlashcard,
  DailyTop3Item,
  HabitItem,
  EnergyMoodLog,
  QuickCaptureNote,
} from '@/types'

export const INITIAL_JOBS: JobApplication[] = [
  {
    id: 'job-1',
    company: '字节跳动',
    role: '大模型算法工程师',
    department: 'Data-AI Lab',
    location: '北京',
    applyDate: '2026-08-15',
    status: 'interview2',
    salary: '35k-45k * 15薪 + 期权',
    jobUrl: 'https://job.bytedance.com',
    source: '牛客内推',
    interviews: [
      {
        id: 'iv-1',
        round: '技术一面',
        date: '2026-08-22',
        time: '14:30',
        interviewer: '资深算法专家',
        questions: [
          '手写 Self-Attention 和 FlashAttention 原理与显存瓶颈推导',
          'Transformer 中 RoPE 位置编码与 ALiBi 的差异及外推能力',
          'LeetCode 25. K个一组翻转链表 (AC)',
        ],
        feedback: '基础扎实，论文细节讲得很清晰，通过一面。',
        rating: 5,
      },
      {
        id: 'iv-2',
        round: '技术二面',
        date: '2026-09-03',
        time: '16:00',
        interviewer: '业务架构负责人',
        questions: [
          'RLHF 与 DPO 算法差异，PPO 中的 KL 惩罚项作用',
          'MoE 架构中的负载均衡损失设计与通信开销优化',
        ],
        feedback: '待进行',
      },
    ],
    notes: '核心意向团队，重点准备分布式训练及 SFT/RLHF 踩坑经验。',
    updatedAt: '2026-08-25T10:00:00Z',
    tags: ['大模型', 'NLP', '核心意向'],
  },
  {
    id: 'job-2',
    company: '腾讯',
    role: '后台开发工程师',
    department: 'TEG 技术工程事业群',
    location: '深圳',
    applyDate: '2026-08-10',
    status: 'hr',
    salary: '30k-38k * 16薪 + 房补',
    source: '官网投递',
    interviews: [
      {
        id: 'iv-3',
        round: '一面',
        date: '2026-08-18',
        questions: ['TCP三次握手与四次挥手', 'Redis跳表与B+树对比', '手撕无重复字符的最长子串'],
        feedback: '通过',
        rating: 5,
      },
      {
        id: 'iv-4',
        round: '二面',
        date: '2026-08-26',
        questions: ['高并发限流熔断算法', '分布式事务 Raft 协议'],
        feedback: '通过，进入 HR 面',
        rating: 4,
      },
    ],
    notes: '已完成技术面，预计这周沟通意向。',
    updatedAt: '2026-08-28T14:20:00Z',
    tags: ['分布式', 'C++', '高可用'],
  },
  {
    id: 'job-3',
    company: '阿里巴巴',
    role: 'Java 后端开发',
    department: '淘天集团',
    location: '杭州',
    applyDate: '2026-08-20',
    status: 'assessment',
    source: '微信群内推',
    notes: '已收到笔试通知，周末完成 3 道编程题。',
    updatedAt: '2026-08-22T09:00:00Z',
    tags: ['Java', '电商'],
  },
  {
    id: 'job-4',
    company: '华为',
    role: '通用软件开发 / AI 工程师',
    department: '计算产品线',
    location: '上海',
    applyDate: '2026-08-05',
    status: 'offer',
    salary: '15-16级，年包 45w+',
    source: '高校宣讲会',
    interviews: [
      {
        id: 'iv-5',
        round: '专业一面',
        date: '2026-08-12',
        questions: ['C++ 内存管理', '手撕拓扑排序'],
        rating: 5,
      },
      {
        id: 'iv-6',
        round: '业务主管面',
        date: '2026-08-19',
        questions: ['科研经历与抗压能力', '未来职业规划'],
        rating: 5,
      },
    ],
    notes: '已发保底两方意向，10月底前签三方。',
    updatedAt: '2026-08-30T16:00:00Z',
    tags: ['保底', '高薪'],
  },
  {
    id: 'job-5',
    company: '美团',
    role: '搜索推荐算法',
    department: '核心本地商业',
    location: '北京',
    applyDate: '2026-08-18',
    status: 'applied',
    notes: '简历初筛通过，等待分配面试官。',
    updatedAt: '2026-08-20T11:00:00Z',
    tags: ['搜推', '算法'],
  },
  {
    id: 'job-6',
    company: '微软 (Microsoft)',
    role: 'Software Engineer',
    department: 'STCA',
    location: '苏州',
    applyDate: '2026-08-01',
    status: 'interview1',
    salary: '年包 38w + 股票 + 36天年假 (WLB极佳)',
    source: 'LinkedIn',
    notes: '注重英文沟通与 LeetCode 纯算法能力。',
    updatedAt: '2026-08-27T08:30:00Z',
    tags: ['外企', 'WLB', '神仙假'],
  },
  {
    id: 'job-7',
    company: '商汤科技',
    role: '计算机视觉研究员',
    department: '通用视觉研究所',
    location: '上海',
    applyDate: '2026-07-28',
    status: 'rejected',
    notes: '一面后由于岗位 HC 缩减被告知暂不匹配。',
    updatedAt: '2026-08-10T17:00:00Z',
    tags: ['CV', '已归档'],
  },
]

export const INITIAL_THESIS: ThesisInfo = {
  title: '基于大语言模型的长上下文多模态推理与高效微调机制研究',
  blindReviewDate: '2027-03-15',
  defenseDate: '2027-05-20',
  chapters: [
    {
      id: 'ch-1',
      title: '第一章 绪论 (背景、意义、主要贡献与结构安排)',
      targetWords: 6000,
      currentWords: 5500,
      status: 'drafted',
      notes: '核心创新点 3 條已提炼完毕，需补全国内外研究现状。',
    },
    {
      id: 'ch-2',
      title: '第二章 相关工作与理论基础 (Transformer、注意力机制与对齐)',
      targetWords: 8000,
      currentWords: 7200,
      status: 'revised',
      notes: '公式已全部规范化 LaTeX，引用补充至 2026 最新顶会。',
    },
    {
      id: 'ch-3',
      title: '第三章 高效长文本多头交叉注意力压缩架构设计 (核心创新一)',
      targetWords: 10000,
      currentWords: 9200,
      status: 'drafted',
      notes: '理论推导部分完成，附图架构清晰。',
    },
    {
      id: 'ch-4',
      title: '第四章 资源约束下的多阶段参数高效微调方法 (核心创新二)',
      targetWords: 9000,
      currentWords: 4200,
      status: 'in_progress',
      notes: '正在补充消融实验部分文字分析。',
    },
    {
      id: 'ch-5',
      title: '第五章 实验设计、系统评测与结果分析',
      targetWords: 12000,
      currentWords: 6800,
      status: 'in_progress',
      notes: 'Main Results 表格完成，正在补对比雷达图和 Case Study。',
    },
    {
      id: 'ch-6',
      title: '第六章 总结与未来工作展望',
      targetWords: 3000,
      currentWords: 0,
      status: 'not_started',
      notes: '待前五章定稿后统一收尾。',
    },
  ],
}

export const INITIAL_MODELS: ModelExperiment[] = [
  {
    id: 'exp-1',
    modelName: 'LLaMA-3-8B-LongContext-Compress-v2',
    taskType: '长文本问答与推理',
    dataset: 'L-Eval / Needle In A Haystack / GSM8K',
    hyperparameters: 'lr: 2e-5, batch: 64, seq_len: 32k, lora_r: 64, warmup: 0.05',
    metrics: 'Accuracy: 88.4% (Baseline+4.2%), Retrieval: 99.1%, Latency: -32%',
    status: 'completed',
    date: '2026-08-28',
    notes: '核心实验，指标优于现有 Baseline，可直接作为论文 Table 2。',
  },
  {
    id: 'exp-2',
    modelName: 'Qwen-2.5-7B-DPO-Multimodal-Align',
    taskType: '多模态偏好对齐',
    dataset: 'MM-Preference-Bench (自建 10k)',
    hyperparameters: 'beta: 0.1, lr: 5e-6, epoch: 3, LoRA alpha: 128',
    metrics: 'Win Rate: 68.3% vs GPT-4V, Hallucination Loss: 0.14',
    status: 'training',
    date: '2026-09-01',
    notes: '8卡 A800 正在跑第 2 个 epoch，目前 Loss 平稳下降。',
  },
  {
    id: 'exp-3',
    modelName: 'Mistral-7B-Quant-FP8-Ablation',
    taskType: 'FP8量化与推理加速消融实验',
    dataset: 'MMLU / HumanEval',
    hyperparameters: 'FP8-E4M3, SmoothQuant alpha: 0.8',
    metrics: 'Pass@1: 52.1% (Lossless < 0.3%)',
    status: 'completed',
    date: '2026-08-20',
    notes: '用于章节 4.4 的消融实验论证。',
  },
]

export const INITIAL_PROJECTS: ResearchProject[] = [
  {
    id: 'proj-1',
    name: 'Long-Agent: 支撑科研论文的高并发分布式长文本推理评测系统',
    description: '论文核心算法配套的开源推理评测框架，集成多模态加载与高并发流水线。',
    techStack: ['Python', 'PyTorch', 'vLLM', 'FastAPI', 'Next.js'],
    progress: 75,
    repoUrl: 'https://github.com/my-repo/long-agent',
    tasks: [
      { id: 't-1', text: '完成 vLLM PagedAttention 自定义算子接入', done: true },
      { id: 't-2', text: '编写长文本评测基准自动化脚本 (Needle/L-Eval)', done: true },
      { id: 't-3', text: '搭建 WebUI 可视化对比演示界面', done: true },
      { id: 't-4', text: '完成 README.md 与开源开源协议准备', done: false },
    ],
  },
  {
    id: 'proj-2',
    name: 'Lab-Cluster 实验集群任务调度与自动化备份脚本',
    description: '用于管理实验室多卡服务器的训练任务调度、日志监控和模型权重持久化备份。',
    techStack: ['Shell', 'Python', 'Docker', 'Ray'],
    progress: 90,
    tasks: [
      { id: 't-5', text: '配置显卡显存超限飞书机器人告警', done: true },
      { id: 't-6', text: '自动化同步 Checkpoint 到 NAS 存储', done: true },
    ],
  },
]

export const INITIAL_MILESTONES: MilestoneItem[] = [
  {
    id: 'ms-1',
    title: '硕士学位论文开题答辩',
    targetDate: '2025-11-15',
    completed: true,
    category: '开题',
    notes: '评审成绩优秀，专家建议深化消融实验。',
  },
  {
    id: 'ms-2',
    title: '硕士学位论文中期检查',
    targetDate: '2026-06-20',
    completed: true,
    category: '中期',
    notes: '核心方法实验基本完成，获得学院通过。',
  },
  {
    id: 'ms-3',
    title: '秋招金九银十冲刺期 (意向确认与签约)',
    targetDate: '2026-10-31',
    completed: false,
    category: '其他',
    notes: '争取拿到 2-3 个头部大厂意向书并完成选 offer。',
  },
  {
    id: 'ms-4',
    title: '学位论文初稿交付导师一审',
    targetDate: '2027-01-10',
    completed: false,
    category: '预答辩',
    notes: '必须完成全部 6 个章节的撰写与图表排版。',
  },
  {
    id: 'ms-5',
    title: '学位论文盲审双向送审（学院硬性红线）',
    targetDate: '2027-03-15',
    completed: false,
    category: '盲审',
    notes: '查重率必须严格控制在 5% 以内。',
  },
  {
    id: 'ms-6',
    title: '硕士研究生毕业正式答辩',
    targetDate: '2027-05-20',
    completed: false,
    category: '答辩',
    notes: '完成学位授予审核与离校手续。',
  },
]

export const INITIAL_LEETCODE: LeetCodeItem[] = [
  {
    id: 'lc-1',
    number: 25,
    title: 'K 个一组翻转链表',
    difficulty: 'Hard',
    tags: ['链表', '递归', '高频'],
    lastReviewed: '2026-08-25',
    nextReview: '2026-09-02',
    reviewStage: 3,
    notes: '核心是维护 pre, cur, next 以及头尾指针接驳，注意剩余不足 k 个时的不翻转处理。',
  },
  {
    id: 'lc-2',
    number: 42,
    title: '接雨水',
    difficulty: 'Hard',
    tags: ['双指针', '单调栈', '动态规划'],
    lastReviewed: '2026-08-28',
    nextReview: '2026-09-04',
    reviewStage: 2,
    notes: '双指针法空间复杂度 O(1)，左右两侧维护 max_left 和 max_right，短板决定容量。',
  },
  {
    id: 'lc-3',
    number: 300,
    title: '最长递增子序列 (LIS)',
    difficulty: 'Medium',
    tags: ['二分查找', '动态规划'],
    lastReviewed: '2026-08-30',
    nextReview: '2026-09-01',
    reviewStage: 1,
    notes: '贪心 + 二分查找 tails 数组，O(N log N) 解法。',
  },
  {
    id: 'lc-4',
    number: 200,
    title: '岛屿数量',
    difficulty: 'Medium',
    tags: ['DFS', 'BFS', '并查集'],
    lastReviewed: '2026-08-20',
    nextReview: '2026-09-03',
    reviewStage: 4,
    notes: '沉岛思想，把访问过的 1 置为 0 避免额外 visited 空间开销。',
  },
]

export const INITIAL_FLASHCARDS: KnowledgeFlashcard[] = [
  {
    id: 'fc-1',
    category: '大模型与深度学习',
    question: '为什么 Multi-Head Attention (MHA) 计算显存瓶颈在 KV Cache？FlashAttention 的优化核心是什么？',
    answer: '自回归生成每步需要保留历史 Token 的 K 和 V 矩阵，序列变长时显存占用线性增长并受限于 GPU HBM 带宽。FlashAttention 利用 Tiling 分块计算与 Softmax 在线更新，将计算融合在高速 SRAM 中，避免了多次读写慢速 HBM，大幅降低显存带宽压力。',
    mastery: 'mastered',
    lastReviewDate: '2026-08-30',
  },
  {
    id: 'fc-2',
    category: '计算机网络与操作系统',
    question: 'TIME_WAIT 状态为什么需要等待 2MSL？过多会有什么危害？',
    answer: '1. 保证最后一个 ACK 报文能到达对方，防止服务端无法正常关闭；2. 防止“已失效的连接请求报文段”出现在本连接中影响新连接。危害：占用大量本地端口号和 socket 资源导致新连接无法建立。',
    mastery: 'medium',
    lastReviewDate: '2026-08-29',
  },
  {
    id: 'fc-3',
    category: 'MySQL 与 Redis',
    question: 'MySQL 事务隔离级别与 MVCC 是如何解决可重复读（RR）幻读的？',
    answer: 'MVCC 通过 Undo Log 版本链 + ReadView（在事务第一次 SELECT 时生成快照）实现一致性快照读；通过 Next-Key Lock（记录锁 + 间隙锁 Gap Lock）在当前读时锁住记录和区间，防止并发插入导致幻读。',
    mastery: 'mastered',
    lastReviewDate: '2026-08-27',
  },
]

export const INITIAL_TOP3: DailyTop3Item[] = [
  { id: 'top-1', text: '完成字节跳动大模型二面复盘与 FlashAttention 重点推导', done: false, category: 'career' },
  { id: 'top-2', text: '修改论文第 4 章节消融实验文字与图表排版', done: false, category: 'research' },
  { id: 'top-3', text: '复习 3 道 Hard 题（接雨水、K个一组翻转链表、编辑距离）', done: true, category: 'study' },
]

export const INITIAL_HABITS: HabitItem[] = [
  {
    id: 'h-1',
    name: 'LeetCode 刷题打卡',
    color: '#10b981',
    icon: 'Code',
    logs: {
      '2026-08-25': true,
      '2026-08-26': true,
      '2026-08-27': true,
      '2026-08-28': true,
      '2026-08-29': false,
      '2026-08-30': true,
      '2026-08-31': true,
      '2026-09-01': true,
    },
  },
  {
    id: 'h-2',
    name: '论文/科研写作 > 1h',
    color: '#6366f1',
    icon: 'BookOpen',
    logs: {
      '2026-08-26': true,
      '2026-08-27': true,
      '2026-08-28': true,
      '2026-08-30': true,
      '2026-09-01': true,
    },
  },
  {
    id: 'h-3',
    name: '早起 8:00 / 运动锻炼',
    color: '#f59e0b',
    icon: 'Flame',
    logs: {
      '2026-08-27': true,
      '2026-08-28': true,
      '2026-08-31': true,
      '2026-09-01': true,
    },
  },
]

export const INITIAL_NOTES: QuickCaptureNote[] = [
  {
    id: 'note-1',
    content: '字节一面被问到：RoPE 为什么在旋转矩阵正交的情况下内积依然保持相对位置不变？答案核心是基于复数乘法在极坐标系下的旋转相加特性。需记在八股复习本中！',
    createdAt: '2026-08-23 15:40',
    tags: ['面试复盘', '大模型'],
  },
  {
    id: 'note-2',
    content: '导师提醒：第 5 章实验部分要把 Baseline 的开源代码 commit hash 附在脚注里，盲审专家看重可复现性。',
    createdAt: '2026-08-29 11:20',
    tags: ['导师意见', '毕业论文'],
  },
]
